/* Generated By:JavaCC: Do not edit this line. GameParserConstants.java */
package edu.curtin.saed.assignment2.Parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GameParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SIZE = 5;
  /** RegularExpression Id. */
  int START = 6;
  /** RegularExpression Id. */
  int GOAL = 7;
  /** RegularExpression Id. */
  int ITEM = 8;
  /** RegularExpression Id. */
  int OBSTACLE = 9;
  /** RegularExpression Id. */
  int PLUGIN = 10;
  /** RegularExpression Id. */
  int SCRIPT = 11;
  /** RegularExpression Id. */
  int AT = 12;
  /** RegularExpression Id. */
  int MESSAGE = 13;
  /** RegularExpression Id. */
  int REQUIRES = 14;
  /** RegularExpression Id. */
  int LBRACE = 15;
  /** RegularExpression Id. */
  int RBRACE = 16;
  /** RegularExpression Id. */
  int LPAREN = 17;
  /** RegularExpression Id. */
  int RPAREN = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int EXCLAM = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int NUMBER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"size\"",
    "\"start\"",
    "\"goal\"",
    "\"item\"",
    "\"obstacle\"",
    "\"plugin\"",
    "\"script\"",
    "\"at\"",
    "\"message\"",
    "\"requires\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"!\"",
    "<STRING>",
    "<NUMBER>",
  };

}
